# Generated by Django 4.2.7 on 2025-09-17 09:24

from django.db import migrations, models
import tool_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to=tool_app.models.upload_to_files)),
                ('converted_file', models.FileField(blank=True, null=True, upload_to=tool_app.models.upload_to_files)),
                ('conversion_type', models.CharField(choices=[('txt_to_pdf', 'Text to PDF'), ('pdf_to_txt', 'PDF to Text'), ('doc_to_pdf', 'DOC to PDF'), ('pdf_to_doc', 'PDF to DOC')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
