# Generated by Django 4.2.7 on 2025-09-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileconversion',
            name='conversion_type',
            field=models.CharField(choices=[('txt_to_pdf', 'Text to PDF'), ('pdf_to_txt', 'PDF to Text'), ('doc_to_pdf', 'DOC to PDF'), ('pdf_to_doc', 'PDF to DOC'), ('image_compress', 'Image Compression'), ('image_convert', 'Image Format Conversion'), ('qr_generate', 'QR Code Generation')], max_length=20),
        ),
    ]
