# Generated by Django 4.2.7 on 2025-09-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_app', '0002_alter_fileconversion_conversion_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileconversion',
            name='conversion_type',
            field=models.CharField(choices=[('txt_to_pdf', 'Text to PDF'), ('pdf_to_txt', 'PDF to Text'), ('doc_to_pdf', 'DOC to PDF'), ('pdf_to_doc', 'PDF to DOC'), ('image_compress', 'Image Compression'), ('image_convert', 'Image Format Conversion'), ('qr_generate', 'QR Code Generation'), ('meta_tag_generator', 'Meta Tag Generator'), ('url_encoder', 'URL Encoder'), ('url_decoder', 'URL Decoder'), ('domain_ip_resolver', 'Domain to IP Resolver'), ('whois_lookup', 'Whois Lookup'), ('robots_sitemap_generator', 'Robots.txt & Sitemap Generator')], max_length=30),
        ),
    ]
