# Generated by Django 4.2.7 on 2025-09-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_app', '0004_alter_fileconversion_conversion_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address for newsletter subscription', max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is subscription active')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, help_text='Date and time of subscription')),
                ('unsubscribed_at', models.DateTimeField(blank=True, help_text='Date and time of unsubscription', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of subscriber', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent of subscriber', null=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscription',
                'verbose_name_plural': 'Newsletter Subscriptions',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
